version: '3'

services:
  client:
    build: frontend
    container_name: client
    ports:
      - '8080:8080'
    networks:
      - app-network

  server:
    build: backend
    container_name: server
    environment:
      - PORT=5000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=your_secure_jwt_secret_here
      - MONGO_URI=mongodb+srv://mateo:Pepe1324@thekingdom.2z5fs.mongodb.net/mern_ecommerce
    ports:
      - '5000:5000'
    command: [
        'sh',
        '-c',
        'npm run seed:db admin@example.com admin123 && npm start'
      ] # Default email and password arguments to database seed script - update your admin email and password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
